import { Box, Center, Flex, Heading, Text } from "@chakra-ui/react";
import Head from "next/head";
import Link from "next/link";

const DemoLink = ({ href, title, text }) => (
  <Center w={400} h={300}>
    <Link href={href}>
      <a>
        <Box
          _hover={{
            bg: "gray.100",
          }}
          border="1px"
          borderColor="darkgray"
          p={4}
          borderRadius="4px"
        >
          <Heading as="h2" textAlign="center">
            {title}
          </Heading>
          <Text>{text}</Text>
        </Box>
      </a>
    </Link>
  </Center>
);

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Heading as="h1" mb={8} textAlign="center">
          Welcome to <a href="https://nextjs.org">Next.js!</a> &amp;{" "}
          <a href="https://www.flagship.io">Flagship</a> Demo
        </Heading>

        <Flex alignItems="center" justifyContent="center">
          <DemoLink
            href="/ssr"
            title="SSR Example"
            text="Go to the Server-Side generated example"
          />
          <DemoLink
            href="/ssg"
            title="SSG Example"
            text="Go to the Static-Side generated example"
          />
        </Flex>
      </main>

      <footer></footer>
    </div>
  );
}
